import { Question } from './supabase';

export const allQuestions: Question[] = [
  // ============ HISTORIA - NIVEL FÁCIL ============
  {
    id: 'h_f_1',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿Cuál es la capital de la provincia de Méndez?',
    question_en: 'What is the capital of Méndez province?',
    option_a_es: 'Tarija',
    option_a_en: 'Tarija',
    option_b_es: 'San Lorenzo',
    option_b_en: 'San Lorenzo',
    option_c_es: 'Villa Montes',
    option_c_en: 'Villa Montes',
    option_d_es: 'Entre Ríos',
    option_d_en: 'Entre Ríos',
    correct_answer: 'b'
  },
  {
    id: 'h_f_2',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿En qué país se encuentra la provincia de Méndez?',
    question_en: 'In which country is Méndez province located?',
    option_a_es: 'Argentina',
    option_a_en: 'Argentina',
    option_b_es: 'Chile',
    option_b_en: 'Chile',
    option_c_es: 'Bolivia',
    option_c_en: 'Bolivia',
    option_d_es: 'Perú',
    option_d_en: 'Peru',
    correct_answer: 'c'
  },
  {
    id: 'h_f_3',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿Qué río atraviesa la provincia de Méndez?',
    question_en: 'What river crosses Méndez province?',
    option_a_es: 'Río San Lorenzo',
    option_a_en: 'San Lorenzo River',
    option_b_es: 'Río Guadalquivir',
    option_b_en: 'Guadalquivir River',
    option_c_es: 'Río Pilaya',
    option_c_en: 'Pilaya River',
    option_d_es: 'Río Amazonas',
    option_d_en: 'Amazon River',
    correct_answer: 'b'
  },
  {
    id: 'h_f_4',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿Qué caudillo luchó por la independencia en la región de Méndez?',
    question_en: 'Which caudillo fought for independence in the Méndez region?',
    option_a_es: 'Eustaquio Méndez',
    option_a_en: 'Eustaquio Méndez',
    option_b_es: 'Simón Bolívar',
    option_b_en: 'Simón Bolívar',
    option_c_es: 'Antonio José de Sucre',
    option_c_en: 'Antonio José de Sucre',
    option_d_es: 'José de la Serna',
    option_d_en: 'José de la Serna',
    correct_answer: 'a'
  },
  {
    id: 'h_f_5',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿En qué año se fundó San Lorenzo?',
    question_en: 'In what year was San Lorenzo founded?',
    option_a_es: '1600',
    option_a_en: '1600',
    option_b_es: '1700',
    option_b_en: '1700',
    option_c_es: '1800',
    option_c_en: '1800',
    option_d_es: '1945',
    option_d_en: '1945',
    correct_answer: 'd'
  },
  {
    id: 'h_f_6',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿Qué batalla marcó la caída de Eustaquio Méndez?',
    question_en: 'What battle marked the fall of Eustaquio Méndez?',
    option_a_es: 'Batalla de Santa Bárbara',
    option_a_en: 'Battle of Santa Bárbara',
    option_b_es: 'Batalla de Ayohuma',
    option_b_en: 'Battle of Ayohuma',
    option_c_es: 'Batalla de Suipacha',
    option_c_en: 'Battle of Suipacha',
    option_d_es: 'Batalla de La Tablada',
    option_d_en: 'Battle of La Tablada',
    correct_answer: 'a'
  },
  {
    id: 'h_f_7',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿Qué caudillo luchó junto a Eustaquio Méndez en la independencia?',
    question_en: 'Which caudillo fought alongside Eustaquio Méndez in the independence?',
    option_a_es: 'Martín Miguel de Güemes',
    option_a_en: 'Martín Miguel de Güemes',
    option_b_es: 'Juan José Vallejos',
    option_b_en: 'Juan José Vallejos',
    option_c_es: 'José Perales',
    option_c_en: 'José Perales',
    option_d_es: 'Ramón Cabrera',
    option_d_en: 'Ramón Cabrera',
    correct_answer: 'a'
  },
  {
    id: 'h_f_8',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿En qué año se cambió el nombre de la provincia de San Lorenzo a Méndez?',
    question_en: 'In what year was the province name changed from San Lorenzo to Méndez?',
    option_a_es: '1876',
    option_a_en: '1876',
    option_b_es: '1945',
    option_b_en: '1945',
    option_c_es: '1947',
    option_c_en: '1947',
    option_d_es: '2000',
    option_d_en: '2000',
    correct_answer: 'b'
  },
  {
    id: 'h_f_9',
    category: 'historia',
    difficulty: 'facil',
    question_es: '¿Cuál era la actividad principal de los habitantes de Méndez durante la colonia?',
    question_en: 'What was the main activity of Méndez inhabitants during colonial times?',
    option_a_es: 'Industria minera',
    option_a_en: 'Mining industry',
    option_b_es: 'Agricultura y ganadería',
    option_b_en: 'Agriculture and livestock',
    option_c_es: 'Comercio marítimo',
    option_c_en: 'Maritime trade',
    option_d_es: 'Textilería',
    option_d_en: 'Textile industry',
    correct_answer: 'b'
  },
  
  // ============ FLORA - NIVEL FÁCIL ============
  {
    id: 'fl_f_1',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Cuál es un árbol típico de la provincia de Méndez?',
    question_en: 'What is a typical tree of Méndez province?',
    option_a_es: 'Algarrobo',
    option_a_en: 'Carob tree',
    option_b_es: 'Queñoa',
    option_b_en: 'Queñoa',
    option_c_es: 'Nogal',
    option_c_en: 'Walnut tree',
    option_d_es: 'Pino',
    option_d_en: 'Pine',
    correct_answer: 'c'
  },
  {
    id: 'fl_f_2',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Qué planta se utiliza en la medicina tradicional de la región?',
    question_en: 'What plant is used in traditional medicine in the region?',
    option_a_es: 'Manzanilla',
    option_a_en: 'Chamomile',
    option_b_es: 'Aloe vera',
    option_b_en: 'Aloe vera',
    option_c_es: 'Lavanda',
    option_c_en: 'Lavender',
    option_d_es: 'Romero',
    option_d_en: 'Rosemary',
    correct_answer: 'a'
  },
  {
    id: 'fl_f_3',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Qué fruta es común en la provincia de Méndez?',
    question_en: 'What fruit is common in Méndez province?',
    option_a_es: 'Mango',
    option_a_en: 'Mango',
    option_b_es: 'Uva',
    option_b_en: 'Grape',
    option_c_es: 'Piña',
    option_c_en: 'Pineapple',
    option_d_es: 'Lima',
    option_d_en: 'Lime',
    correct_answer: 'b'
  },
  {
    id: 'fl_f_4',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Qué cactus se encuentra en la región de Méndez?',
    question_en: 'What cactus is found in the Méndez region?',
    option_a_es: 'Sahuayo',
    option_a_en: 'Saguaro',
    option_b_es: 'Cardón',
    option_b_en: 'Cardón',
    option_c_es: 'Nopal',
    option_c_en: 'Nopal',
    option_d_es: 'Pitaya',
    option_d_en: 'Pitaya',
    correct_answer: 'b'
  },
  {
    id: 'fl_f_5',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Qué flor es emblemática de la provincia de Méndez?',
    question_en: 'What flower is emblematic of Méndez province?',
    option_a_es: 'Rosa',
    option_a_en: 'Rose',
    option_b_es: 'Clavel',
    option_b_en: 'Carnation',
    option_c_es: 'Rosa Pascua',
    option_c_en: 'Easter Rose',
    option_d_es: 'Lirio',
    option_d_en: 'Lily',
    correct_answer: 'c'
  },
  {
    id: 'fl_f_6',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Qué planta es típica en los jardines de Tarija?',
    question_en: 'What plant is typical in Tarija gardens?',
    option_a_es: 'Margarita',
    option_a_en: 'Daisy',
    option_b_es: 'Rosas',
    option_b_en: 'Roses',
    option_c_es: 'Tulipán',
    option_c_en: 'Tulip',
    option_d_es: 'Orquídea',
    option_d_en: 'Orchid',
    correct_answer: 'b'
  },
  {
    id: 'fl_f_7',
    category: 'flora',
    difficulty: 'facil',
    question_es: '¿Qué árbol es común en las áreas rurales de Méndez?',
    question_en: 'What tree is common in rural areas of Méndez?',
    option_a_es: 'Sauce',
    option_a_en: 'Willow',
    option_b_es: 'Eucalipto',
    option_b_en: 'Eucalyptus',
    option_c_es: 'Algarrobo',
    option_c_en: 'Carob tree',
    option_d_es: 'Pino',
    option_d_en: 'Pine',
    correct_answer: 'a'
  },

  // ============ FAUNA - NIVEL FÁCIL ============
  {
    id: 'fa_f_1',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué animal es típico del departamento de Tarija?',
    question_en: 'What animal is typical of Tarija department?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'La Vaca',
    option_b_en: 'The Cow',
    option_c_es: 'Cóndor',
    option_c_en: 'Condor',
    option_d_es: 'Llama',
    option_d_en: 'Llama',
    correct_answer: 'b'
  },
  {
    id: 'fa_f_2',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué ave es común en la Provincia de Méndez?',
    question_en: 'What bird is common in Méndez Province?',
    option_a_es: 'Águila',
    option_a_en: 'Eagle',
    option_b_es: 'Tucán',
    option_b_en: 'Toucan',
    option_c_es: 'Flamenco',
    option_c_en: 'Flamingo',
    option_d_es: 'Loro',
    option_d_en: 'Parrot',
    correct_answer: 'd'
  },
  {
    id: 'fa_f_3',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué pez habita en los ríos de la provincia de Méndez?',
    question_en: 'What fish lives in the rivers of Méndez province?',
    option_a_es: 'Misquinchitos',
    option_a_en: 'Misquinchitos',
    option_b_es: 'Trucha',
    option_b_en: 'Trout',
    option_c_es: 'Piraña',
    option_c_en: 'Piranha',
    option_d_es: 'Dorado',
    option_d_en: 'Dorado',
    correct_answer: 'a'
  },
  {
    id: 'fa_f_4',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué insecto es común en la región de Méndez?',
    question_en: 'What insect is common in the Méndez region?',
    option_a_es: 'Mariposa',
    option_a_en: 'Butterfly',
    option_b_es: 'Abeja',
    option_b_en: 'Bee',
    option_c_es: 'Mosquito',
    option_c_en: 'Mosquito',
    option_d_es: 'Escarabajo',
    option_d_en: 'Beetle',
    correct_answer: 'b'
  },
  {
    id: 'fa_f_5',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué insecto ayuda a la polinización en los valles?',
    question_en: 'What insect helps pollination in the valleys?',
    option_a_es: 'Abeja',
    option_a_en: 'Bee',
    option_b_es: 'Mariposa monarca',
    option_b_en: 'Monarch butterfly',
    option_c_es: 'Mosquito',
    option_c_en: 'Mosquito',
    option_d_es: 'Grillo',
    option_d_en: 'Cricket',
    correct_answer: 'a'
  },
  {
    id: 'fa_f_6',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué reptil pequeño se encuentra en zonas rocosas?',
    question_en: 'What small reptile is found in rocky areas?',
    option_a_es: 'Lagartija',
    option_a_en: 'Lizard',
    option_b_es: 'Boa',
    option_b_en: 'Boa',
    option_c_es: 'Cocodrilo',
    option_c_en: 'Crocodile',
    option_d_es: 'Tortuga gigante',
    option_d_en: 'Giant turtle',
    correct_answer: 'a'
  },
  {
    id: 'fa_f_7',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué mamífero doméstico es común en las chacras?',
    question_en: 'What domestic mammal is common on farms?',
    option_a_es: 'Burro',
    option_a_en: 'Donkey',
    option_b_es: 'Caballo salvaje',
    option_b_en: 'Wild horse',
    option_c_es: 'Zorro',
    option_c_en: 'Fox',
    option_d_es: 'Cuy',
    option_d_en: 'Guinea pig',
    correct_answer: 'a'
  },
  {
    id: 'fa_f_8',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué ave anuncia el amanecer en Méndez?',
    question_en: 'What bird announces dawn in Méndez?',
    option_a_es: 'Gallo',
    option_a_en: 'Rooster',
    option_b_es: 'Paloma',
    option_b_en: 'Dove',
    option_c_es: 'Loro',
    option_c_en: 'Parrot',
    option_d_es: 'Gaviota',
    option_d_en: 'Seagull',
    correct_answer: 'a'
  },
  {
    id: 'fa_f_9',
    category: 'fauna',
    difficulty: 'facil',
    question_es: '¿Qué animal representa la vida del campo chapaco?',
    question_en: 'What animal represents the life of the chapaco countryside?',
    option_a_es: 'Vaca',
    option_a_en: 'Cow',
    option_b_es: 'Panda',
    option_b_en: 'Panda',
    option_c_es: 'Tigre',
    option_c_en: 'Tiger',
    option_d_es: 'Mono',
    option_d_en: 'Monkey',
    correct_answer: 'a'
  },

  // ============ MÚSICA - NIVEL FÁCIL ============
  {
    id: 'm_f_1',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué instrumento musical es característico de la provincia de Méndez?',
    question_en: 'What musical instrument is characteristic of Méndez province?',
    option_a_es: 'Charango',
    option_a_en: 'Charango',
    option_b_es: 'Erke',
    option_b_en: 'Erke',
    option_c_es: 'Guitarra',
    option_c_en: 'Guitar',
    option_d_es: 'Quena',
    option_d_en: 'Quena',
    correct_answer: 'b'
  },
  {
    id: 'm_f_2',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué género musical se interpreta en las festividades de Méndez?',
    question_en: 'What musical genre is played at Méndez festivities?',
    option_a_es: 'Salsa',
    option_a_en: 'Salsa',
    option_b_es: 'Cumbia',
    option_b_en: 'Cumbia',
    option_c_es: 'Folklore',
    option_c_en: 'Folklore',
    option_d_es: 'Rock',
    option_d_en: 'Rock',
    correct_answer: 'c'
  },
  {
    id: 'm_f_3',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué danza se baila en las festividades de Méndez?',
    question_en: 'What dance is performed at Méndez festivities?',
    option_a_es: 'Cueca',
    option_a_en: 'Cueca',
    option_b_es: 'Diablada',
    option_b_en: 'Diablada',
    option_c_es: 'Morenada',
    option_c_en: 'Morenada',
    option_d_es: 'Tinku',
    option_d_en: 'Tinku',
    correct_answer: 'a'
  },
  {
    id: 'm_f_4',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué festividad se celebra con zapateo de violín en la provincia de Méndez?',
    question_en: 'What festivity is celebrated with violin zapateo in Méndez province?',
    option_a_es: 'Carnaval',
    option_a_en: 'Carnival',
    option_b_es: 'Pascua Florida',
    option_b_en: 'Easter',
    option_c_es: 'Fiesta de la Independencia',
    option_c_en: 'Independence Day',
    option_d_es: 'Fiesta de Moto Méndez',
    option_d_en: 'Moto Méndez Festival',
    correct_answer: 'b'
  },
  {
    id: 'm_f_5',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué canción es popular en la región de Méndez?',
    question_en: 'What song is popular in the Méndez region?',
    option_a_es: 'La Cañada',
    option_a_en: 'La Cañada',
    option_b_es: 'El Toro',
    option_b_en: 'El Toro',
    option_c_es: 'La Chapaca',
    option_c_en: 'La Chapaca',
    option_d_es: 'Moto Méndez',
    option_d_en: 'Moto Méndez',
    correct_answer: 'd'
  },
  {
    id: 'm_f_6',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué baile se realiza en las festividades de navidad en la Provincia Méndez?',
    question_en: 'What dance is performed at Christmas festivities in Méndez Province?',
    option_a_es: 'Adoraciones',
    option_a_en: 'Adoraciones',
    option_b_es: 'Diablada',
    option_b_en: 'Diablada',
    option_c_es: 'Morenada',
    option_c_en: 'Morenada',
    option_d_es: 'Tinku',
    option_d_en: 'Tinku',
    correct_answer: 'a'
  },
  {
    id: 'm_f_7',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué instrumento se utiliza en las adoraciones?',
    question_en: 'What instrument is used in adoraciones?',
    option_a_es: 'Charango',
    option_a_en: 'Charango',
    option_b_es: 'Quenilla',
    option_b_en: 'Quenilla',
    option_c_es: 'Guitarra',
    option_c_en: 'Guitar',
    option_d_es: 'Quena',
    option_d_en: 'Quena',
    correct_answer: 'b'
  },
  {
    id: 'm_f_8',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué festividad se celebra en San Lorenzo en honor a Eustaquio Méndez?',
    question_en: 'What festivity is celebrated in San Lorenzo in honor of Eustaquio Méndez?',
    option_a_es: 'Carnaval',
    option_a_en: 'Carnival',
    option_b_es: 'Pascua Florida',
    option_b_en: 'Easter',
    option_c_es: 'Fiesta de la Independencia',
    option_c_en: 'Independence Day',
    option_d_es: 'Natalicio de Moto Méndez',
    option_d_en: 'Birth of Moto Méndez',
    correct_answer: 'd'
  },
  {
    id: 'm_f_9',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué instrumento NO pertenece a la música tarijeña?',
    question_en: 'What instrument does NOT belong to Tarija music?',
    option_a_es: 'Erque',
    option_a_en: 'Erque',
    option_b_es: 'Guitarra',
    option_b_en: 'Guitar',
    option_c_es: 'Saxofón',
    option_c_en: 'Saxophone',
    option_d_es: 'Charango',
    option_d_en: 'Charango',
    correct_answer: 'c'
  },
  {
    id: 'm_f_10',
    category: 'musica',
    difficulty: 'facil',
    question_es: '¿Qué instrumento se toca para el carnaval Méndeño?',
    question_en: 'What instrument is played for the Méndez carnival?',
    option_a_es: 'Charango',
    option_a_en: 'Charango',
    option_b_es: 'La Caja',
    option_b_en: 'The Drum',
    option_c_es: 'Guitarra',
    option_c_en: 'Guitar',
    option_d_es: 'Quena',
    option_d_en: 'Quena',
    correct_answer: 'b'
  },

  // ============ HISTORIA - NIVEL INTERMEDIO ============
  {
    id: 'h_i_1',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué provincia boliviana es conocida por la valentía de Eustaquio Méndez?',
    question_en: 'What Bolivian province is known for the bravery of Eustaquio Méndez?',
    option_a_es: 'Provincia Méndez',
    option_a_en: 'Méndez Province',
    option_b_es: 'Gran Chaco',
    option_b_en: 'Gran Chaco',
    option_c_es: 'Provincia Cercado',
    option_c_en: 'Cercado Province',
    option_d_es: 'Provincia O\'Connor',
    option_d_en: 'O\'Connor Province',
    correct_answer: 'a'
  },
  {
    id: 'h_i_2',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué papel tuvo Eustaquio Méndez en la independencia de Bolivia?',
    question_en: 'What role did Eustaquio Méndez play in Bolivia\'s independence?',
    option_a_es: 'Gobernador colonial',
    option_a_en: 'Colonial governor',
    option_b_es: 'Caudillo patriota',
    option_b_en: 'Patriot caudillo',
    option_c_es: 'Sacerdote',
    option_c_en: 'Priest',
    option_d_es: 'Comerciante',
    option_d_en: 'Merchant',
    correct_answer: 'b'
  },
  {
    id: 'h_i_3',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Cuál fue el principal enemigo de Méndez durante la guerra de independencia?',
    question_en: 'Who was Méndez\'s main enemy during the war of independence?',
    option_a_es: 'El ejército español',
    option_a_en: 'The Spanish army',
    option_b_es: 'Argentinos',
    option_b_en: 'Argentinians',
    option_c_es: 'Brasileños',
    option_c_en: 'Brazilians',
    option_d_es: 'Incas',
    option_d_en: 'Incas',
    correct_answer: 'a'
  },
  {
    id: 'h_i_4',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué importancia tiene la Batalla de Santa Bárbara?',
    question_en: 'What is the importance of the Battle of Santa Bárbara?',
    option_a_es: 'Victoria de España',
    option_a_en: 'Spanish victory',
    option_b_es: 'Liberación de Sudamérica del dominio realista',
    option_b_en: 'Liberation of South America from royalist rule',
    option_c_es: 'Fundación de Tarija',
    option_c_en: 'Foundation of Tarija',
    option_d_es: 'Independencia de Argentina',
    option_d_en: 'Independence of Argentina',
    correct_answer: 'b'
  },
  {
    id: 'h_i_5',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué institución lideró la defensa de Méndez en la independencia?',
    question_en: 'What institution led the defense of Méndez in the independence?',
    option_a_es: 'Ejército independentista',
    option_a_en: 'Independence army',
    option_b_es: 'Alcaldía local',
    option_b_en: 'Local mayor\'s office',
    option_c_es: 'Iglesia Católica',
    option_c_en: 'Catholic Church',
    option_d_es: 'Comercio colonial',
    option_d_en: 'Colonial trade',
    correct_answer: 'a'
  },
  {
    id: 'h_i_6',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Cuál era la economía principal en la provincia Méndez durante el siglo XIX?',
    question_en: 'What was the main economy in Méndez province during the 19th century?',
    option_a_es: 'Minería',
    option_a_en: 'Mining',
    option_b_es: 'Agricultura y ganadería',
    option_b_en: 'Agriculture and livestock',
    option_c_es: 'Comercio internacional',
    option_c_en: 'International trade',
    option_d_es: 'Pesca',
    option_d_en: 'Fishing',
    correct_answer: 'b'
  },
  {
    id: 'h_i_7',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué héroe nacional nació en la provincia de Méndez?',
    question_en: 'What national hero was born in Méndez province?',
    option_a_es: 'Juana Azurduy',
    option_a_en: 'Juana Azurduy',
    option_b_es: 'Eustaquio Méndez',
    option_b_en: 'Eustaquio Méndez',
    option_c_es: 'Andrés de Santa Cruz',
    option_c_en: 'Andrés de Santa Cruz',
    option_d_es: 'Pedro Blanco',
    option_d_en: 'Pedro Blanco',
    correct_answer: 'b'
  },
  {
    id: 'h_i_8',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué río fue estratégico durante la independencia de Tarija?',
    question_en: 'What river was strategic during Tarija\'s independence?',
    option_a_es: 'Río Pilcomayo',
    option_a_en: 'Pilcomayo River',
    option_b_es: 'Río Guadalquivir',
    option_b_en: 'Guadalquivir River',
    option_c_es: 'Río Paraguay',
    option_c_en: 'Paraguay River',
    option_d_es: 'Río Amazonas',
    option_d_en: 'Amazon River',
    correct_answer: 'b'
  },
  {
    id: 'h_i_9',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué festividad se celebra en San Lorenzo relacionada con la historia?',
    question_en: 'What festivity is celebrated in San Lorenzo related to history?',
    option_a_es: 'Fiesta de Carnaval',
    option_a_en: 'Carnival',
    option_b_es: 'Fiesta de San Lorenzo',
    option_b_en: 'San Lorenzo Festival',
    option_c_es: 'Fiesta de la Vendimia',
    option_c_en: 'Harvest Festival',
    option_d_es: 'Día del Trabajo',
    option_d_en: 'Labor Day',
    correct_answer: 'b'
  },
  {
    id: 'h_i_10',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué tipo de armas utilizaba Eustaquio Méndez y sus tropas?',
    question_en: 'What type of weapons did Eustaquio Méndez and his troops use?',
    option_a_es: 'Pistolas y espadas',
    option_a_en: 'Pistols and swords',
    option_b_es: 'Arcos y flechas',
    option_b_en: 'Bows and arrows',
    option_c_es: 'Lanzas de madera',
    option_c_en: 'Wooden spears',
    option_d_es: 'Cañones de hierro',
    option_d_en: 'Iron cannons',
    correct_answer: 'a'
  },
  {
    id: 'h_i_11',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué grupo apoyó a los patriotas en Méndez?',
    question_en: 'What group supported the patriots in Méndez?',
    option_a_es: 'Indígenas y criollos',
    option_a_en: 'Indigenous and creoles',
    option_b_es: 'Solo españoles',
    option_b_en: 'Only Spanish',
    option_c_es: 'Solo militares extranjeros',
    option_c_en: 'Only foreign military',
    option_d_es: 'Comerciantes locales',
    option_d_en: 'Local merchants',
    correct_answer: 'a'
  },
  {
    id: 'h_i_12',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Qué estrategia militar era común en la provincia durante la independencia?',
    question_en: 'What military strategy was common in the province during independence?',
    option_a_es: 'Guerrillas y emboscadas',
    option_a_en: 'Guerrillas and ambushes',
    option_b_es: 'Batallas navales',
    option_b_en: 'Naval battles',
    option_c_es: 'Fortificaciones de piedra',
    option_c_en: 'Stone fortifications',
    option_d_es: 'Uso de artillería pesada',
    option_d_en: 'Use of heavy artillery',
    correct_answer: 'a'
  },
  {
    id: 'h_i_13',
    category: 'historia',
    difficulty: 'intermedio',
    question_es: '¿Cuál fue el legado de Eustaquio Méndez para Tarija?',
    question_en: 'What was Eustaquio Méndez\'s legacy for Tarija?',
    option_a_es: 'Fundación de San Lorenzo',
    option_a_en: 'Foundation of San Lorenzo',
    option_b_es: 'Caudillo de la independencia y héroe de la batalla de la tablada',
    option_b_en: 'Independence caudillo and hero of the battle of la tablada',
    option_c_es: 'Creación de ríos',
    option_c_en: 'Creation of rivers',
    option_d_es: 'Introducción de cultivos europeos',
    option_d_en: 'Introduction of European crops',
    correct_answer: 'b'
  },

  // ============ FLORA - NIVEL INTERMEDIO ============
  {
    id: 'fl_i_1',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué árbol nativo de Méndez es resistente a la sequía?',
    question_en: 'What native tree of Méndez is resistant to drought?',
    option_a_es: 'Algarrobo',
    option_a_en: 'Carob tree',
    option_b_es: 'Cedro',
    option_b_en: 'Cedar',
    option_c_es: 'Pino',
    option_c_en: 'Pine',
    option_d_es: 'Queñoa',
    option_d_en: 'Queñoa',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_2',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué planta medicinal es típica de Tarija?',
    question_en: 'What medicinal plant is typical of Tarija?',
    option_a_es: 'Manzanilla',
    option_a_en: 'Chamomile',
    option_b_es: 'Lavanda',
    option_b_en: 'Lavender',
    option_c_es: 'Aloe vera',
    option_c_en: 'Aloe vera',
    option_d_es: 'Romero',
    option_d_en: 'Rosemary',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_3',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Cuál es una fruta común de los valles de Méndez?',
    question_en: 'What is a common fruit of the Méndez valleys?',
    option_a_es: 'Uva',
    option_a_en: 'Grape',
    option_b_es: 'Piña',
    option_b_en: 'Pineapple',
    option_c_es: 'Mango',
    option_c_en: 'Mango',
    option_d_es: 'Limón',
    option_d_en: 'Lemon',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_4',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué cactus es característico del clima seco de Méndez?',
    question_en: 'What cactus is characteristic of Méndez\'s dry climate?',
    option_a_es: 'Cardón',
    option_a_en: 'Cardón',
    option_b_es: 'Nopal',
    option_b_en: 'Nopal',
    option_c_es: 'Sahuayo',
    option_c_en: 'Saguaro',
    option_d_es: 'Pitaya',
    option_d_en: 'Pitaya',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_5',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué árbol se utiliza para sombra en los campos de cultivo?',
    question_en: 'What tree is used for shade in crop fields?',
    option_a_es: 'Taco',
    option_a_en: 'Taco',
    option_b_es: 'Eucalipto',
    option_b_en: 'Eucalyptus',
    option_c_es: 'Cedro',
    option_c_en: 'Cedar',
    option_d_es: 'Queñoa',
    option_d_en: 'Queñoa',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_6',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué planta se usa tradicionalmente en infusiones contra resfriados?',
    question_en: 'What plant is traditionally used in infusions against colds?',
    option_a_es: 'Manzanilla',
    option_a_en: 'Chamomile',
    option_b_es: 'Lavanda',
    option_b_en: 'Lavender',
    option_c_es: 'Menta',
    option_c_en: 'Mint',
    option_d_es: 'Romero',
    option_d_en: 'Rosemary',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_7',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué fruta de la Provincia Méndez se exporta por su sabor dulce?',
    question_en: 'What fruit from Méndez Province is exported for its sweet flavor?',
    option_a_es: 'Frutilla',
    option_a_en: 'Strawberry',
    option_b_es: 'Durazno',
    option_b_en: 'Peach',
    option_c_es: 'Mango',
    option_c_en: 'Mango',
    option_d_es: 'Piña',
    option_d_en: 'Pineapple',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_8',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué árbol crece en las áreas más áridas de Méndez?',
    question_en: 'What tree grows in the most arid areas of Méndez?',
    option_a_es: 'Chañar',
    option_a_en: 'Chañar',
    option_b_es: 'Cedro',
    option_b_en: 'Cedar',
    option_c_es: 'Queñoa',
    option_c_en: 'Queñoa',
    option_d_es: 'Pino',
    option_d_en: 'Pine',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_9',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué planta es usada en ceremonias tradicionales de Provincias Méndez?',
    question_en: 'What plant is used in traditional ceremonies in Méndez Provinces?',
    option_a_es: 'Rosa',
    option_a_en: 'Rose',
    option_b_es: 'Rosas Pascuas',
    option_b_en: 'Easter Roses',
    option_c_es: 'Tulipán',
    option_c_en: 'Tulip',
    option_d_es: 'Clavel',
    option_d_en: 'Carnation',
    correct_answer: 'b'
  },
  {
    id: 'fl_i_10',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué planta es resistente al clima seco de Méndez?',
    question_en: 'What plant is resistant to Méndez\'s dry climate?',
    option_a_es: 'Cactus',
    option_a_en: 'Cactus',
    option_b_es: 'Lirio',
    option_b_en: 'Lily',
    option_c_es: 'Rosa',
    option_c_en: 'Rose',
    option_d_es: 'Tulipán',
    option_d_en: 'Tulip',
    correct_answer: 'a'
  },
  {
    id: 'fl_i_11',
    category: 'flora',
    difficulty: 'intermedio',
    question_es: '¿Qué fruta se cultiva en terrazas de los valles de Tarija?',
    question_en: 'What fruit is grown on terraces in the Tarija valleys?',
    option_a_es: 'Durazno',
    option_a_en: 'Peach',
    option_b_es: 'Piña',
    option_b_en: 'Pineapple',
    option_c_es: 'Mango',
    option_c_en: 'Mango',
    option_d_es: 'Banana',
    option_d_en: 'Banana',
    correct_answer: 'a'
  },

  // ============ FAUNA - NIVEL INTERMEDIO ============
  {
    id: 'fa_i_1',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Cuál de las siguientes especies de mamíferos se encuentra en peligro de extinción en el departamento de Tarija?',
    question_en: 'Which of the following mammal species is in danger of extinction in Tarija department?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Jaguar',
    option_b_en: 'Jaguar',
    option_c_es: 'Oso andino (jukumari)',
    option_c_en: 'Andean bear (jukumari)',
    option_d_es: 'Zorro andino',
    option_d_en: 'Andean fox',
    correct_answer: 'c'
  },
  {
    id: 'fa_i_2',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de loro se encuentra en peligro crítico en el departamento de Tarija?',
    question_en: 'What parrot species is in critical danger in Tarija department?',
    option_a_es: 'Ara militaris',
    option_a_en: 'Ara militaris',
    option_b_es: 'Amazona tucumana',
    option_b_en: 'Amazona tucumana',
    option_c_es: 'Amazona viridis',
    option_c_en: 'Amazona viridis',
    option_d_es: 'Ara glaucogularis',
    option_d_en: 'Ara glaucogularis',
    correct_answer: 'd'
  },
  {
    id: 'fa_i_3',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Cuál de los siguientes mamíferos es conocido por su capacidad para trepar árboles en Tarija?',
    question_en: 'Which of the following mammals is known for its ability to climb trees in Tarija?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Jaguar',
    option_b_en: 'Jaguar',
    option_c_es: 'Oso andino (jukumari)',
    option_c_en: 'Andean bear (jukumari)',
    option_d_es: 'Zorro andino',
    option_d_en: 'Andean fox',
    correct_answer: 'c'
  },
  {
    id: 'fa_i_4',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de pez es comúnmente encontrada en los ríos del departamento de Tarija?',
    question_en: 'What fish species is commonly found in the rivers of Tarija department?',
    option_a_es: 'Sábalo',
    option_a_en: 'Shad',
    option_b_es: 'Pacú',
    option_b_en: 'Pacu',
    option_c_es: 'Dorado',
    option_c_en: 'Dorado',
    option_d_es: 'Bagre',
    option_d_en: 'Catfish',
    correct_answer: 'a'
  },
  {
    id: 'fa_i_5',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de felino es conocida por su sigilosa caza en la región de Tarija?',
    question_en: 'What feline species is known for its stealthy hunting in the Tarija region?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Jaguar',
    option_b_en: 'Jaguar',
    option_c_es: 'Ocelote',
    option_c_en: 'Ocelot',
    option_d_es: 'Gato montés',
    option_d_en: 'Wildcat',
    correct_answer: 'a'
  },
  {
    id: 'fa_i_6',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Cuál de las siguientes especies de primates se encuentra en la región de Tarija?',
    question_en: 'Which of the following primate species is found in the Tarija region?',
    option_a_es: 'Mono capuchino',
    option_a_en: 'Capuchin monkey',
    option_b_es: 'Mono araña',
    option_b_en: 'Spider monkey',
    option_c_es: 'Mono silbador (Sapajus apella)',
    option_c_en: 'Howler monkey (Sapajus apella)',
    option_d_es: 'Mono titi',
    option_d_en: 'Titi monkey',
    correct_answer: 'c'
  },
  {
    id: 'fa_i_7',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de ave rapaz es común en las zonas montañosas de Tarija?',
    question_en: 'What bird of prey species is common in the mountainous areas of Tarija?',
    option_a_es: 'Águila real',
    option_a_en: 'Golden eagle',
    option_b_es: 'Cóndor andino (Vultur gryphus)',
    option_b_en: 'Andean condor (Vultur gryphus)',
    option_c_es: 'Halcón peregrino',
    option_c_en: 'Peregrine falcon',
    option_d_es: 'Búho real',
    option_d_en: 'Great horned owl',
    correct_answer: 'b'
  },
  {
    id: 'fa_i_8',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de armadillo es característica de la región de Tarija?',
    question_en: 'What armadillo species is characteristic of the Tarija region?',
    option_a_es: 'Armadillo gigante',
    option_a_en: 'Giant armadillo',
    option_b_es: 'Armadillo de nueve bandas',
    option_b_en: 'Nine-banded armadillo',
    option_c_es: 'Quirquincho (Dasypodidae)',
    option_c_en: 'Quirquincho (Dasypodidae)',
    option_d_es: 'Armadillo peludo',
    option_d_en: 'Hairy armadillo',
    correct_answer: 'c'
  },
  {
    id: 'fa_i_9',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de felino es conocida por su pelaje moteado en la región de Tarija?',
    question_en: 'What feline species is known for its spotted fur in the Tarija region?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Jaguar (Panthera onca)',
    option_b_en: 'Jaguar (Panthera onca)',
    option_c_es: 'Ocelote',
    option_c_en: 'Ocelot',
    option_d_es: 'Gato montés',
    option_d_en: 'Wildcat',
    correct_answer: 'b'
  },
  {
    id: 'fa_i_10',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de loro es endémica de las zonas subtropicales de Tarija?',
    question_en: 'What parrot species is endemic to the subtropical zones of Tarija?',
    option_a_es: 'Loro hablador (Amazona tucumana)',
    option_a_en: 'Talkative parrot (Amazona tucumana)',
    option_b_es: 'Loro de cabeza azul',
    option_b_en: 'Blue-headed parrot',
    option_c_es: 'Loro de pecho rojo',
    option_c_en: 'Red-breasted parrot',
    option_d_es: 'Loro de pico amarillo',
    option_d_en: 'Yellow-billed parrot',
    correct_answer: 'a'
  },
  {
    id: 'fa_i_11',
    category: 'fauna',
    difficulty: 'intermedio',
    question_es: '¿Qué especie de felino es conocida por su pelaje rayado en la región de Tarija?',
    question_en: 'What feline species is known for its striped fur in the Tarija region?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Jaguar',
    option_b_en: 'Jaguar',
    option_c_es: 'Tigre',
    option_c_en: 'Tiger',
    option_d_es: 'Gato andino (Felis jacobita)',
    option_d_en: 'Andean cat (Felis jacobita)',
    correct_answer: 'd'
  },

  // ============ MÚSICA - NIVEL INTERMEDIO ============
  {
    id: 'm_i_1',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué instrumento típico de Tarija se utiliza en fiestas folklóricas?',
    question_en: 'What typical instrument of Tarija is used in folkloric festivities?',
    option_a_es: 'Charango',
    option_a_en: 'Charango',
    option_b_es: 'Erke',
    option_b_en: 'Erke',
    option_c_es: 'Guitarra',
    option_c_en: 'Guitar',
    option_d_es: 'Quena',
    option_d_en: 'Quena',
    correct_answer: 'b'
  },
  {
    id: 'm_i_2',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué género musical es más popular en la provincia de Méndez?',
    question_en: 'What musical genre is most popular in Méndez province?',
    option_a_es: 'Folklore',
    option_a_en: 'Folklore',
    option_b_es: 'Rock',
    option_b_en: 'Rock',
    option_c_es: 'Salsa',
    option_c_en: 'Salsa',
    option_d_es: 'Cumbia',
    option_d_en: 'Cumbia',
    correct_answer: 'a'
  },
  {
    id: 'm_i_3',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué danza es típica de las festividades de San Lorenzo?',
    question_en: 'What dance is typical of San Lorenzo festivities?',
    option_a_es: 'Cueca',
    option_a_en: 'Cueca',
    option_b_es: 'Morenada',
    option_b_en: 'Morenada',
    option_c_es: 'Diablada',
    option_c_en: 'Diablada',
    option_d_es: 'Tinku',
    option_d_en: 'Tinku',
    correct_answer: 'a'
  },
  {
    id: 'm_i_4',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué festividad se celebra con el violín en la Provincia Méndez?',
    question_en: 'What festivity is celebrated with the violin in Méndez Province?',
    option_a_es: 'Carnaval',
    option_a_en: 'Carnival',
    option_b_es: 'La Pascua',
    option_b_en: 'Easter',
    option_c_es: 'Día del Trabajo',
    option_c_en: 'Labor Day',
    option_d_es: 'Fiesta de la Vendimia',
    option_d_en: 'Harvest Festival',
    correct_answer: 'b'
  },
  {
    id: 'm_i_5',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué canción es emblemática en la provincia de Méndez?',
    question_en: 'What song is emblematic in Méndez province?',
    option_a_es: 'Moto Méndez',
    option_a_en: 'Moto Méndez',
    option_b_es: 'La Cañada',
    option_b_en: 'La Cañada',
    option_c_es: 'El Toro',
    option_c_en: 'El Toro',
    option_d_es: 'La Chapaca',
    option_d_en: 'La Chapaca',
    correct_answer: 'a'
  },
  {
    id: 'm_i_6',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué instrumento de viento se utiliza en celebraciones folklóricas?',
    question_en: 'What wind instrument is used in folkloric celebrations?',
    option_a_es: 'Flauta dulce',
    option_a_en: 'Recorder',
    option_b_es: 'Erke',
    option_b_en: 'Erke',
    option_c_es: 'Saxofón',
    option_c_en: 'Saxophone',
    option_d_es: 'Trompeta',
    option_d_en: 'Trumpet',
    correct_answer: 'b'
  },
  {
    id: 'm_i_7',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué danza se interpreta con trajes tradicionales en la Provincia Méndez?',
    question_en: 'What dance is performed with traditional costumes in Méndez Province?',
    option_a_es: 'Cueca',
    option_a_en: 'Cueca',
    option_b_es: 'Diablada',
    option_b_en: 'Diablada',
    option_c_es: 'Tinku',
    option_c_en: 'Tinku',
    option_d_es: 'Morenada',
    option_d_en: 'Morenada',
    correct_answer: 'a'
  },
  {
    id: 'm_i_8',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué música se escucha durante la Fiesta de Moto Méndez?',
    question_en: 'What music is heard during the Moto Méndez Festival?',
    option_a_es: 'Folklore',
    option_a_en: 'Folklore',
    option_b_es: 'Rock',
    option_b_en: 'Rock',
    option_c_es: 'Salsa',
    option_c_en: 'Salsa',
    option_d_es: 'Pop',
    option_d_en: 'Pop',
    correct_answer: 'a'
  },
  {
    id: 'm_i_9',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué instrumento acompaña al canto folklórico en la provincia?',
    question_en: 'What instrument accompanies folkloric singing in the province?',
    option_a_es: 'Charango',
    option_a_en: 'Charango',
    option_b_es: 'Piano',
    option_b_en: 'Piano',
    option_c_es: 'Violín',
    option_c_en: 'Violin',
    option_d_es: 'Guitarra eléctrica',
    option_d_en: 'Electric guitar',
    correct_answer: 'a'
  },
  {
    id: 'm_i_10',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué estilo musical combina instrumentos nativos y danza?',
    question_en: 'What musical style combines native instruments and dance?',
    option_a_es: 'Folklore',
    option_a_en: 'Folklore',
    option_b_es: 'Cumbia',
    option_b_en: 'Cumbia',
    option_c_es: 'Jazz',
    option_c_en: 'Jazz',
    option_d_es: 'Rock',
    option_d_en: 'Rock',
    correct_answer: 'a'
  },
  {
    id: 'm_i_11',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué evento mantiene viva la tradición musical en Méndez?',
    question_en: 'What event keeps the musical tradition alive in Méndez?',
    option_a_es: 'Fiesta de San Lorenzo',
    option_a_en: 'San Lorenzo Festival',
    option_b_es: 'Carnaval de Oruro',
    option_b_en: 'Oruro Carnival',
    option_c_es: 'Feria del Libro',
    option_c_en: 'Book Fair',
    option_d_es: 'Festival de Cine',
    option_d_en: 'Film Festival',
    correct_answer: 'a'
  },
  {
    id: 'm_i_12',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué instrumento es de gran tradición en la provincia de Tarija?',
    question_en: 'What instrument is of great tradition in Tarija province?',
    option_a_es: 'Guitarra',
    option_a_en: 'Guitar',
    option_b_es: 'Erke',
    option_b_en: 'Erke',
    option_c_es: 'Piano',
    option_c_en: 'Piano',
    option_d_es: 'Trompeta',
    option_d_en: 'Trumpet',
    correct_answer: 'b'
  },
  {
    id: 'm_i_13',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué baile folklórico simboliza la identidad cultural de Méndez?',
    question_en: 'What folkloric dance symbolizes the cultural identity of Méndez?',
    option_a_es: 'Cueca',
    option_a_en: 'Cueca',
    option_b_es: 'Diablada',
    option_b_en: 'Diablada',
    option_c_es: 'Tinku',
    option_c_en: 'Tinku',
    option_d_es: 'Morenada',
    option_d_en: 'Morenada',
    correct_answer: 'a'
  },
  {
    id: 'm_i_14',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué celebración combina música, danza y comida típica en Méndez?',
    question_en: 'What celebration combines music, dance and typical food in Méndez?',
    option_a_es: 'Fiesta de San Lorenzo',
    option_a_en: 'San Lorenzo Festival',
    option_b_es: 'Carnaval',
    option_b_en: 'Carnival',
    option_c_es: 'Día del Trabajo',
    option_c_en: 'Labor Day',
    option_d_es: 'Vendimia',
    option_d_en: 'Harvest',
    correct_answer: 'a'
  },
  {
    id: 'm_i_15',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué instrumentos son típicos en la zona "chapaca" que incluye Méndez?',
    question_en: 'What instruments are typical in the "chapaca" zone that includes Méndez?',
    option_a_es: 'Violín y guitarra',
    option_a_en: 'Violin and guitar',
    option_b_es: 'Sitar y tabla',
    option_b_en: 'Sitar and tabla',
    option_c_es: 'Didgeridoo',
    option_c_en: 'Didgeridoo',
    option_d_es: 'Saxofón jazz',
    option_d_en: 'Jazz saxophone',
    correct_answer: 'a'
  },
  {
    id: 'm_i_16',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué traje típico femenino representa a la cultura chapaca, presente en la provincia Méndez?',
    question_en: 'What typical feminine costume represents the chapaca culture, present in Méndez province?',
    option_a_es: 'Kimono japonés',
    option_a_en: 'Japanese kimono',
    option_b_es: 'Sari indio',
    option_b_en: 'Indian sari',
    option_c_es: 'Traje de chapaca',
    option_c_en: 'Chapaca costume',
    option_d_es: 'Dirndl alemán',
    option_d_en: 'German Dirndl',
    correct_answer: 'c'
  },
  {
    id: 'm_i_17',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué baile o ritmo se asocia con la identidad tarijeña-chapaca?',
    question_en: 'What dance or rhythm is associated with the Tarija-chapaca identity?',
    option_a_es: 'Cueca chapaca',
    option_a_en: 'Cueca chapaca',
    option_b_es: 'Samba brasileña',
    option_b_en: 'Brazilian samba',
    option_c_es: 'Tango argentino',
    option_c_en: 'Argentine tango',
    option_d_es: 'Reguetón urbano',
    option_d_en: 'Urban reggaeton',
    correct_answer: 'a'
  },
  {
    id: 'm_i_18',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué manifestación cultural es propia del pueblo de Méndez?',
    question_en: 'What cultural manifestation is typical of the Méndez town?',
    option_a_es: 'Fiesta de la Candelaria',
    option_a_en: 'Candelaria Festival',
    option_b_es: 'Oktoberfest',
    option_b_en: 'Oktoberfest',
    option_c_es: 'Carnaval de Río',
    option_c_en: 'Rio Carnival',
    option_d_es: 'Festival de cine internacional',
    option_d_en: 'International film festival',
    correct_answer: 'a'
  },
  {
    id: 'm_i_19',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿La población de la provincia Méndez "canta, baila y vive con fervor religioso"?',
    question_en: 'Does the population of Méndez province "sing, dance and live with religious fervor"?',
    option_a_es: 'Sí',
    option_a_en: 'Yes',
    option_b_es: 'No',
    option_b_en: 'No',
    option_c_es: 'Solo canta',
    option_c_en: 'Only sings',
    option_d_es: 'Solo baila',
    option_d_en: 'Only dances',
    correct_answer: 'a'
  },
  {
    id: 'm_i_20',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿La provincia Méndez pertenece al sector "chapaco" con clima frío-seco y ascendencia española?',
    question_en: 'Does Méndez province belong to the "chapaco" sector with cold-dry climate and Spanish ancestry?',
    option_a_es: 'Reg-1 norte tropical',
    option_a_en: 'Reg-1 tropical north',
    option_b_es: 'Zona chapaca',
    option_b_en: 'Chapaca zone',
    option_c_es: 'Sub-puna',
    option_c_en: 'Sub-puna',
    option_d_es: 'Amazonía cruceña',
    option_d_en: 'Cruceña Amazon',
    correct_answer: 'b'
  },
  {
    id: 'm_i_21',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué instrumento de viento tradicional aparece en la descripción de la zona chapaca?',
    question_en: 'What traditional wind instrument appears in the description of the chapaca zone?',
    option_a_es: 'Quenilla',
    option_a_en: 'Quenilla',
    option_b_es: 'Didgeridoo',
    option_b_en: 'Didgeridoo',
    option_c_es: 'Clarín militar',
    option_c_en: 'Military bugle',
    option_d_es: 'Ocarina china',
    option_d_en: 'Chinese ocarina',
    correct_answer: 'a'
  },
  {
    id: 'm_i_22',
    category: 'musica',
    difficulty: 'intermedio',
    question_es: '¿Qué característica identifica la música y cultura de la provincia Méndez?',
    question_en: 'What characteristic identifies the music and culture of Méndez province?',
    option_a_es: 'Alegría, identidad y tradición popular',
    option_a_en: 'Joy, identity and popular tradition',
    option_b_es: 'Música electrónica exclusivamente',
    option_b_en: 'Electronic music exclusively',
    option_c_es: 'Fusión hip-hop jazz internacional',
    option_c_en: 'International hip-hop jazz fusion',
    option_d_es: 'Trajes futuristas tecnológicos',
    option_d_en: 'Futuristic technological costumes',
    correct_answer: 'a'
  },

  // ============ HISTORIA - NIVEL DIFÍCIL ============
  {
    id: 'h_d_1',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué tipo de combate utilizó con mayor éxito Eustaquio "Moto" Méndez durante la lucha por la independencia?',
    question_en: 'What type of combat did Eustaquio "Moto" Méndez use most successfully during the independence struggle?',
    option_a_es: 'Combate naval',
    option_a_en: 'Naval combat',
    option_b_es: 'Guerra de guerrillas',
    option_b_en: 'Guerrilla warfare',
    option_c_es: 'Batallas en campo abierto',
    option_c_en: 'Open field battles',
    option_d_es: 'Defensa de fortificaciones',
    option_d_en: 'Defense of fortifications',
    correct_answer: 'b'
  },
  {
    id: 'h_d_2',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿En qué año se consolidó oficialmente la fundación del pueblo de San Lorenzo?',
    question_en: 'In what year was the foundation of the town of San Lorenzo officially consolidated?',
    option_a_es: '1600',
    option_a_en: '1600',
    option_b_es: '1843',
    option_b_en: '1843',
    option_c_es: '1816',
    option_c_en: '1816',
    option_d_es: '1799',
    option_d_en: '1799',
    correct_answer: 'b'
  },
  {
    id: 'h_d_3',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿De qué institución dependía Tarija durante el periodo colonial?',
    question_en: 'What institution did Tarija depend on during the colonial period?',
    option_a_es: 'Audiencia de Charcas',
    option_a_en: 'Audiencia de Charcas',
    option_b_es: 'Capitanía de Buenos Aires',
    option_b_en: 'Captaincy of Buenos Aires',
    option_c_es: 'Virreinato del Perú',
    option_c_en: 'Viceroyalty of Peru',
    option_d_es: 'Gobernación de Cochabamba',
    option_d_en: 'Governorate of Cochabamba',
    correct_answer: 'a'
  },
  {
    id: 'h_d_4',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Por qué la Batalla de Santa Bárbara es recordada en la historia de Tarija?',
    question_en: 'Why is the Battle of Santa Bárbara remembered in Tarija\'s history?',
    option_a_es: 'Fue una derrota significativa',
    option_a_en: 'It was a significant defeat',
    option_b_es: 'Representó la última batalla de Méndez',
    option_b_en: 'It represented Méndez\'s last battle',
    option_c_es: 'Fue el inicio del proceso independentista',
    option_c_en: 'It was the beginning of the independence process',
    option_d_es: 'Se realizó en honor al virrey',
    option_d_en: 'It was held in honor of the viceroy',
    correct_answer: 'b'
  },
  {
    id: 'h_d_5',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué personaje histórico no fue colaborador directo de Eustaquio Méndez?',
    question_en: 'Which historical figure was not a direct collaborator of Eustaquio Méndez?',
    option_a_es: 'Pedro Tejada',
    option_a_en: 'Pedro Tejada',
    option_b_es: 'José Perales',
    option_b_en: 'José Perales',
    option_c_es: 'Juan José Vallejos',
    option_c_en: 'Juan José Vallejos',
    option_d_es: 'Simón Bolívar',
    option_d_en: 'Simón Bolívar',
    correct_answer: 'c'
  },
  {
    id: 'h_d_6',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué elemento natural servía como vía de comunicación entre los pueblos tarijeños durante la colonia?',
    question_en: 'What natural element served as a communication route between Tarija towns during the colony?',
    option_a_es: 'El río Bermejo',
    option_a_en: 'The Bermejo River',
    option_b_es: 'El lago Titicaca',
    option_b_en: 'Lake Titicaca',
    option_c_es: 'El río Pilcomayo',
    option_c_en: 'The Pilcomayo River',
    option_d_es: 'El valle de Sama',
    option_d_en: 'The Sama Valley',
    correct_answer: 'a'
  },
  {
    id: 'h_d_7',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Cuál fue la principal base económica de la provincia Méndez durante el periodo colonial?',
    question_en: 'What was the main economic base of Méndez province during the colonial period?',
    option_a_es: 'La agricultura y la ganadería',
    option_a_en: 'Agriculture and livestock',
    option_b_es: 'La minería de oro',
    option_b_en: 'Gold mining',
    option_c_es: 'La pesca fluvial',
    option_c_en: 'River fishing',
    option_d_es: 'El comercio marítimo',
    option_d_en: 'Maritime trade',
    correct_answer: 'a'
  },
  {
    id: 'h_d_8',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué valor simboliza la figura de Eustaquio Méndez para el pueblo tarijeño?',
    question_en: 'What value does the figure of Eustaquio Méndez symbolize for the Tarija people?',
    option_a_es: 'Patriotismo y valentía',
    option_a_en: 'Patriotism and bravery',
    option_b_es: 'Fe religiosa',
    option_b_en: 'Religious faith',
    option_c_es: 'Prosperidad económica',
    option_c_en: 'Economic prosperity',
    option_d_es: 'Conocimiento científico',
    option_d_en: 'Scientific knowledge',
    correct_answer: 'a'
  },
  {
    id: 'h_d_9',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Cómo se mantiene viva la memoria de Moto Méndez en San Lorenzo?',
    question_en: 'How is the memory of Moto Méndez kept alive in San Lorenzo?',
    option_a_es: 'A través de fiestas patronales y actos cívicos',
    option_a_en: 'Through patron saint festivals and civic acts',
    option_b_es: 'Por medio de esculturas',
    option_b_en: 'Through sculptures',
    option_c_es: 'En programas escolares',
    option_c_en: 'In school programs',
    option_d_es: 'En ferias ganaderas',
    option_d_en: 'In livestock fairs',
    correct_answer: 'a'
  },
  {
    id: 'h_d_10',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué rasgo de la influencia española aún puede observarse en San Lorenzo?',
    question_en: 'What trait of Spanish influence can still be observed in San Lorenzo?',
    option_a_es: 'La arquitectura colonial y la religiosidad popular',
    option_a_en: 'Colonial architecture and popular religiosity',
    option_b_es: 'Los trajes típicos europeos',
    option_b_en: 'Typical European costumes',
    option_c_es: 'La gastronomía italiana',
    option_c_en: 'Italian gastronomy',
    option_d_es: 'Las costumbres árabes',
    option_d_en: 'Arab customs',
    correct_answer: 'a'
  },
  {
    id: 'h_d_11',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Por qué Tarija se unió a la lucha independentista en el siglo XIX?',
    question_en: 'Why did Tarija join the independence struggle in the 19th century?',
    option_a_es: 'Por los abusos y tributos impuestos por los españoles',
    option_a_en: 'Due to abuses and tributes imposed by the Spanish',
    option_b_es: 'Por la expansión del comercio',
    option_b_en: 'For trade expansion',
    option_c_es: 'Por influencia francesa',
    option_c_en: 'Due to French influence',
    option_d_es: 'Por rivalidad con Potosí',
    option_d_en: 'Due to rivalry with Potosí',
    correct_answer: 'a'
  },
  {
    id: 'h_d_12',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué lugar representa hoy un símbolo histórico de la lucha por la libertad en Méndez?',
    question_en: 'What place today represents a historical symbol of the struggle for freedom in Méndez?',
    option_a_es: 'La Casa Moto Méndez',
    option_a_en: 'The Moto Méndez House',
    option_b_es: 'El mercado campesino',
    option_b_en: 'The peasant market',
    option_c_es: 'El puente Bermejo',
    option_c_en: 'The Bermejo bridge',
    option_d_es: 'La iglesia de San Roque',
    option_d_en: 'The church of San Roque',
    correct_answer: 'a'
  },
  {
    id: 'h_d_13',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué actividad fortaleció la identidad local después de la independencia?',
    question_en: 'What activity strengthened local identity after independence?',
    option_a_es: 'Las fiestas patrias en honor a los héroes tarijeños',
    option_a_en: 'The patriotic festivals in honor of Tarija heroes',
    option_b_es: 'La minería regional',
    option_b_en: 'Regional mining',
    option_c_es: 'El comercio exterior',
    option_c_en: 'Foreign trade',
    option_d_es: 'La educación europea',
    option_d_en: 'European education',
    correct_answer: 'a'
  },
  {
    id: 'h_d_14',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Qué estrategia militar utilizaban los patriotas tarijeños para enfrentar a los realistas?',
    question_en: 'What military strategy did Tarija patriots use to confront the royalists?',
    option_a_es: 'Emboscadas y ataques rápidos',
    option_a_en: 'Ambushes and quick attacks',
    option_b_es: 'Combates frontales',
    option_b_en: 'Frontal combats',
    option_c_es: 'Negociaciones pacíficas',
    option_c_en: 'Peaceful negotiations',
    option_d_es: 'Bloqueos económicos',
    option_d_en: 'Economic blockades',
    correct_answer: 'a'
  },
  {
    id: 'h_d_15',
    category: 'historia',
    difficulty: 'dificil',
    question_es: '¿Cuál fue una consecuencia directa de la lucha liderada por Méndez?',
    question_en: 'What was a direct consequence of the struggle led by Méndez?',
    option_a_es: 'El fortalecimiento del espíritu libertario del pueblo',
    option_a_en: 'The strengthening of the libertarian spirit of the people',
    option_b_es: 'El aislamiento político',
    option_b_en: 'Political isolation',
    option_c_es: 'La invasión portuguesa',
    option_c_en: 'The Portuguese invasion',
    option_d_es: 'La pérdida de autonomía',
    option_d_en: 'The loss of autonomy',
    correct_answer: 'a'
  },

  // ============ FLORA - NIVEL DIFÍCIL ============
  {
    id: 'fl_d_1',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué árbol, común en los valles de Méndez, se utiliza para sombra y madera?',
    question_en: 'What tree, common in the valleys of Méndez, is used for shade and wood?',
    option_a_es: 'Algarrobo',
    option_a_en: 'Algarrobo',
    option_b_es: 'Cedro',
    option_b_en: 'Cedar',
    option_c_es: 'Eucalipto',
    option_c_en: 'Eucalyptus',
    option_d_es: 'Sauce',
    option_d_en: 'Willow',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_2',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué planta medicinal es tradicionalmente usada en infusiones para aliviar dolores estomacales?',
    question_en: 'What medicinal plant is traditionally used in infusions to relieve stomach pains?',
    option_a_es: 'Manzanilla',
    option_a_en: 'Chamomile',
    option_b_es: 'Romero',
    option_b_en: 'Rosemary',
    option_c_es: 'Ruda',
    option_c_en: 'Rue',
    option_d_es: 'Cedrón',
    option_d_en: 'Lemon verbena',
    correct_answer: 'd'
  },
  {
    id: 'fl_d_3',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué cultivo agrícola es considerado emblema económico de Tarija?',
    question_en: 'What agricultural crop is considered the economic emblem of Tarija?',
    option_a_es: 'La vid (uva para vino)',
    option_a_en: 'The grapevine (grapes for wine)',
    option_b_es: 'El maíz',
    option_b_en: 'Corn',
    option_c_es: 'El trigo',
    option_c_en: 'Wheat',
    option_d_es: 'El café',
    option_d_en: 'Coffee',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_4',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué flor silvestre representa la belleza de la primavera chapaca?',
    question_en: 'What wild flower represents the beauty of the chapaca spring?',
    option_a_es: 'Flor del lapacho',
    option_a_en: 'Lapacho flower',
    option_b_es: 'Margarita andina',
    option_b_en: 'Andean daisy',
    option_c_es: 'Girasol de valle',
    option_c_en: 'Valley sunflower',
    option_d_es: 'Orquídea serrana',
    option_d_en: 'Highland orchid',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_5',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué planta nativa es utilizada como leña y tiene gran resistencia a la sequía?',
    question_en: 'What native plant is used as firewood and has great drought resistance?',
    option_a_es: 'El churqui',
    option_a_en: 'The churqui',
    option_b_es: 'El nogal',
    option_b_en: 'The walnut tree',
    option_c_es: 'El pino',
    option_c_en: 'The pine',
    option_d_es: 'El toborochi',
    option_d_en: 'The toborochi',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_6',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué planta aromática se cultiva con frecuencia en huertos familiares?',
    question_en: 'What aromatic plant is frequently grown in family gardens?',
    option_a_es: 'Hierba buena',
    option_a_en: 'Spearmint',
    option_b_es: 'Albahaca',
    option_b_en: 'Basil',
    option_c_es: 'Orégano',
    option_c_en: 'Oregano',
    option_d_es: 'Perejil',
    option_d_en: 'Parsley',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_7',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué árbol se asocia con la elaboración artesanal de muebles locales?',
    question_en: 'What tree is associated with the artisanal making of local furniture?',
    option_a_es: 'El nogal',
    option_a_en: 'The walnut tree',
    option_b_es: 'El lapacho',
    option_b_en: 'The lapacho',
    option_c_es: 'El eucalipto',
    option_c_en: 'The eucalyptus',
    option_d_es: 'El algarrobo',
    option_d_en: 'The algarrobo',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_8',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué tipo de vegetación predomina en los alrededores de San Lorenzo?',
    question_en: 'What type of vegetation predominates around San Lorenzo?',
    option_a_es: 'Bosque seco interandino',
    option_a_en: 'Interandean dry forest',
    option_b_es: 'Selva tropical',
    option_b_en: 'Tropical rainforest',
    option_c_es: 'Páramo frío',
    option_c_en: 'Cold páramo',
    option_d_es: 'Sabana húmeda',
    option_d_en: 'Humid savanna',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_9',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué cultivo, además de la vid, es representativo de la agricultura tradicional tarijeña?',
    question_en: 'What crop, besides grapevine, is representative of traditional Tarija agriculture?',
    option_a_es: 'El maíz',
    option_a_en: 'Corn',
    option_b_es: 'El arroz',
    option_b_en: 'Rice',
    option_c_es: 'El café',
    option_c_en: 'Coffee',
    option_d_es: 'El maní',
    option_d_en: 'Peanut',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_10',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Cuál es el rango altitudinal para la fauna de la Reserva Nacional de Flora y Fauna Tariquía, que cubre parte del área andina de Tarija?',
    question_en: 'What is the altitude range for the fauna of the Tariquía National Flora and Fauna Reserve, which covers part of the Andean area of Tarija?',
    option_a_es: '500-3 500 m s.n.m.',
    option_a_en: '500-3,500 m a.s.l.',
    option_b_es: 'Bajo 100 m',
    option_b_en: 'Below 100 m',
    option_c_es: 'Sobre 6 000 m',
    option_c_en: 'Above 6,000 m',
    option_d_es: 'Solo en llanuras costeras',
    option_d_en: 'Only in coastal plains',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_11',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué formación ecológica se encuentra en la vertiente oriental que abarca la fauna de Tarija?',
    question_en: 'What ecological formation is found on the eastern slope that encompasses the fauna of Tarija?',
    option_a_es: 'Bosque tucumano-boliviano',
    option_a_en: 'Tucuman-Bolivian forest',
    option_b_es: 'Tundra ártica',
    option_b_en: 'Arctic tundra',
    option_c_es: 'Selva boreal',
    option_c_en: 'Boreal jungle',
    option_d_es: 'Manglar costero',
    option_d_en: 'Coastal mangrove',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_12',
    category: 'flora',
    difficulty: 'dificil',
    question_es: 'En los huertos tradicionales sanlorenceños, ¿qué planta frutal se considera "de los abuelos" y rara vez se cultiva comercialmente?',
    question_en: 'In traditional San Lorenzo orchards, what fruit plant is considered "from the grandparents" and is rarely grown commercially?',
    option_a_es: 'Membrillo',
    option_a_en: 'Quince',
    option_b_es: 'Durazno',
    option_b_en: 'Peach',
    option_c_es: 'Ciruelo',
    option_c_en: 'Plum',
    option_d_es: 'Manzano',
    option_d_en: 'Apple tree',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_13',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué árbol nativo de San Lorenzo tiene madera tan dura que se usaba para fabricar yugos y herramientas agrícolas?',
    question_en: 'What native tree of San Lorenzo has wood so hard that it was used to make yokes and agricultural tools?',
    option_a_es: 'Quebracho blanco',
    option_a_en: 'White quebracho',
    option_b_es: 'Eucalipto',
    option_b_en: 'Eucalyptus',
    option_c_es: 'Nogal',
    option_c_en: 'Walnut',
    option_d_es: 'Algarrobo',
    option_d_en: 'Algarrobo',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_14',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué tipo de vegetación predomina entre 1.800 y 2.200 m s. n. m. en las quebradas del área de Canasmoro?',
    question_en: 'What type of vegetation predominates between 1,800 and 2,200 m a.s.l. in the ravines of the Canasmoro area?',
    option_a_es: 'Bosque seco montano',
    option_a_en: 'Montane dry forest',
    option_b_es: 'Bosque húmedo subtropical',
    option_b_en: 'Subtropical humid forest',
    option_c_es: 'Chaparral árido',
    option_c_en: 'Arid chaparral',
    option_d_es: 'Bosque espinoso',
    option_d_en: 'Thorny forest',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_15',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué planta silvestre produce flores blancas con fragancia nocturna y se usa en rituales tradicionales?',
    question_en: 'What wild plant produces white flowers with nocturnal fragrance and is used in traditional rituals?',
    option_a_es: 'Jazmín del campo',
    option_a_en: 'Field jasmine',
    option_b_es: 'Lirio de monte',
    option_b_en: 'Mountain lily',
    option_c_es: 'Flor de tuna',
    option_c_en: 'Prickly pear flower',
    option_d_es: 'Retama',
    option_d_en: 'Broom',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_16',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué cultivo, introducido por los españoles, se adaptó a los suelos arenosos de San Lorenzo y se usa para chicha?',
    question_en: 'What crop, introduced by the Spanish, adapted to the sandy soils of San Lorenzo and is used for chicha?',
    option_a_es: 'Maíz',
    option_a_en: 'Corn',
    option_b_es: 'Trigo',
    option_b_en: 'Wheat',
    option_c_es: 'Cebada',
    option_c_en: 'Barley',
    option_d_es: 'Arroz',
    option_d_en: 'Rice',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_17',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué especie arbórea se está reforestando actualmente para proteger microcuencas locales?',
    question_en: 'What tree species is currently being reforested to protect local micro-watersheds?',
    option_a_es: 'Tarco',
    option_a_en: 'Tarco',
    option_b_es: 'Cedro',
    option_b_en: 'Cedar',
    option_c_es: 'Pino',
    option_c_en: 'Pine',
    option_d_es: 'Eucalipto',
    option_d_en: 'Eucalyptus',
    correct_answer: 'a'
  },
  {
    id: 'fl_d_18',
    category: 'flora',
    difficulty: 'dificil',
    question_es: '¿Qué característica hace al "molle" tan importante en los ecosistemas de Tarija?',
    question_en: 'What characteristic makes the "molle" so important in the ecosystems of Tarija?',
    option_a_es: 'Fija nitrógeno al suelo',
    option_a_en: 'Fixes nitrogen to the soil',
    option_b_es: 'Crece solo en suelos húmedos',
    option_b_en: 'Grows only in humid soils',
    option_c_es: 'Produce flores comestibles',
    option_c_en: 'Produces edible flowers',
    option_d_es: 'Se usa para madera',
    option_d_en: 'Is used for wood',
    correct_answer: 'a'
  },

  // ============ FAUNA - NIVEL DIFÍCIL ============
  {
    id: 'fa_d_1',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué animal símbolo de Tarija posee un caparazón protector segmentado?',
    question_en: 'What symbolic animal of Tarija has a segmented protective shell?',
    option_a_es: 'Quirquincho',
    option_a_en: 'Quirquincho',
    option_b_es: 'Puma',
    option_b_en: 'Puma',
    option_c_es: 'Tatú boliviano',
    option_c_en: 'Bolivian armadillo',
    option_d_es: 'Vizcacha',
    option_d_en: 'Vizcacha',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_2',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué ave emblemática surca los cielos de las serranías tarijeñas?',
    question_en: 'What emblematic bird soars through the skies of the Tarija highlands?',
    option_a_es: 'Cóndor andino',
    option_a_en: 'Andean condor',
    option_b_es: 'Paraba frente roja',
    option_b_en: 'Red-fronted macaw',
    option_c_es: 'Tucán del valle',
    option_c_en: 'Valley toucan',
    option_d_es: 'Halcón serrano',
    option_d_en: 'Highland hawk',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_3',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué felino habita en los bosques secos y montes de Tarija?',
    question_en: 'What feline inhabits the dry forests and mountains of Tarija?',
    option_a_es: 'Gato montés',
    option_a_en: 'Wildcat',
    option_b_es: 'Jaguar',
    option_b_en: 'Jaguar',
    option_c_es: 'Lince',
    option_c_en: 'Lynx',
    option_d_es: 'Ocelote',
    option_d_en: 'Ocelot',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_4',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué especie está en peligro de extinción en la provincia mendez?',
    question_en: 'What species is in danger of extinction in the Méndez province?',
    option_a_es: 'El cóndor',
    option_a_en: 'The condor',
    option_b_es: 'Cóndor andino',
    option_b_en: 'Andean condor',
    option_c_es: 'Zorro colorado',
    option_c_en: 'Red fox',
    option_d_es: 'Tatú',
    option_d_en: 'Armadillo',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_5',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué mamífero nocturno excava madrigueras para protegerse del calor diurno?',
    question_en: 'What nocturnal mammal digs burrows to protect itself from daytime heat?',
    option_a_es: 'Quirquincho',
    option_a_en: 'Quirquincho',
    option_b_es: 'Vizcacha',
    option_b_en: 'Vizcacha',
    option_c_es: 'Puma',
    option_c_en: 'Puma',
    option_d_es: 'Conejo andino',
    option_d_en: 'Andean rabbit',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_6',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué ave representa la libertad en la cosmovisión andina?',
    question_en: 'What bird represents freedom in the Andean worldview?',
    option_a_es: 'Cóndor',
    option_a_en: 'Condor',
    option_b_es: 'Paraba',
    option_b_en: 'Macaw',
    option_c_es: 'Lechuza',
    option_c_en: 'Owl',
    option_d_es: 'Martín pescador',
    option_d_en: 'Kingfisher',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_7',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué animal es símbolo en varias danzas folklóricas del sur de Bolivia?',
    question_en: 'What animal is a symbol in several folk dances of southern Bolivia?',
    option_a_es: 'Quirquincho',
    option_a_en: 'Quirquincho',
    option_b_es: 'Zorro',
    option_b_en: 'Fox',
    option_c_es: 'Puma',
    option_c_en: 'Puma',
    option_d_es: 'Tatú',
    option_d_en: 'Armadillo',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_8',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué animal carnívoro cumple un rol en el control natural de plagas?',
    question_en: 'What carnivorous animal plays a role in natural pest control?',
    option_a_es: 'Zorro',
    option_a_en: 'Fox',
    option_b_es: 'Puma',
    option_b_en: 'Puma',
    option_c_es: 'Gato montés',
    option_c_en: 'Wildcat',
    option_d_es: 'Tero',
    option_d_en: 'Southern lapwing',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_9',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué especie de rana tarijeña se adapta a los cambios de temperatura y humedad?',
    question_en: 'What Tarija frog species adapts to changes in temperature and humidity?',
    option_a_es: 'Rana serrana',
    option_a_en: 'Highland frog',
    option_b_es: 'Rana verde',
    option_b_en: 'Green frog',
    option_c_es: 'Rana chapaca',
    option_c_en: 'Chapaca frog',
    option_d_es: 'Rana amazónica',
    option_d_en: 'Amazonian frog',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_10',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué mamífero es cazador solitario de hábitos nocturnos?',
    question_en: 'What mammal is a solitary hunter with nocturnal habits?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Zorro',
    option_b_en: 'Fox',
    option_c_es: 'Tatú',
    option_c_en: 'Armadillo',
    option_d_es: 'Quirquincho',
    option_d_en: 'Quirquincho',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_11',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué función ecológica cumple el quirquincho?',
    question_en: 'What ecological function does the quirquincho fulfill?',
    option_a_es: 'Airear el suelo y controlar insectos',
    option_a_en: 'Aerate the soil and control insects',
    option_b_es: 'Transportar semillas',
    option_b_en: 'Transport seeds',
    option_c_es: 'Polinizar flores',
    option_c_en: 'Pollinate flowers',
    option_d_es: 'Generar abono',
    option_d_en: 'Generate fertilizer',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_12',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué característica comparten el quirquincho y el tatú?',
    question_en: 'What characteristic do the quirquincho and the tatú share?',
    option_a_es: 'Ambos poseen caparazón protector',
    option_a_en: 'Both have a protective shell',
    option_b_es: 'Ambos son herbívoros',
    option_b_en: 'Both are herbivores',
    option_c_es: 'Ambos son aves',
    option_c_en: 'Both are birds',
    option_d_es: 'Ambos viven en agua',
    option_d_en: 'Both live in water',
    correct_answer: 'a'
  },
  {
    id: 'fa_d_13',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Cuál de estos animales vive en las riberas de los ríos de Tarija según fuentes de fauna?',
    question_en: 'Which of these animals lives on the banks of the rivers of Tarija according to fauna sources?',
    option_a_es: 'Oso polar',
    option_a_en: 'Polar bear',
    option_b_es: 'Capibara',
    option_b_en: 'Capybara',
    option_c_es: 'Canguro rojo',
    option_c_en: 'Red kangaroo',
    option_d_es: 'Tigre de Bengala',
    option_d_en: 'Bengal tiger',
    correct_answer: 'b'
  },
  {
    id: 'fa_d_14',
    category: 'fauna',
    difficulty: 'dificil',
    question_es: '¿Qué animal representa el equilibrio ecológico en las montañas de Tarija?',
    question_en: 'What animal represents the ecological balance in the mountains of Tarija?',
    option_a_es: 'Puma',
    option_a_en: 'Puma',
    option_b_es: 'Vizcacha',
    option_b_en: 'Vizcacha',
    option_c_es: 'Tero',
    option_c_en: 'Southern lapwing',
    option_d_es: 'Cóndor',
    option_d_en: 'Condor',
    correct_answer: 'a'
  },

  // ============ MÚSICA - NIVEL DIFÍCIL ============
  {
    id: 'm_d_1',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué instrumento tradicional se interpreta en los carnavales chapacos?',
    question_en: 'What traditional instrument is played in chapaco carnivals?',
    option_a_es: 'Erque',
    option_a_en: 'Erque',
    option_b_es: 'Caja',
    option_b_en: 'Drum',
    option_c_es: 'Quena',
    option_c_en: 'Quena',
    option_d_es: 'Charango',
    option_d_en: 'Charango',
    correct_answer: 'a'
  },
  {
    id: 'm_d_2',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué estilo musical expresa sentimientos de nostalgia y amor en Tarija?',
    question_en: 'What musical style expresses feelings of nostalgia and love in Tarija?',
    option_a_es: 'Tonada chapaca',
    option_a_en: 'Chapaca song',
    option_b_es: 'Huayño',
    option_b_en: 'Huayño',
    option_c_es: 'Saya',
    option_c_en: 'Saya',
    option_d_es: 'Polka',
    option_d_en: 'Polka',
    correct_answer: 'a'
  },
  {
    id: 'm_d_3',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué instrumento acompaña al erque en las fiestas rurales?',
    question_en: 'What instrument accompanies the erque in rural festivals?',
    option_a_es: 'Caja',
    option_a_en: 'Drum',
    option_b_es: 'Guitarra',
    option_b_en: 'Guitar',
    option_c_es: 'Bombo',
    option_c_en: 'Bass drum',
    option_d_es: 'Charango',
    option_d_en: 'Charango',
    correct_answer: 'a'
  },
  {
    id: 'm_d_4',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué ritmo musical de origen argentino fue adoptado en Tarija?',
    question_en: 'What musical rhythm of Argentine origin was adopted in Tarija?',
    option_a_es: 'Chamamé',
    option_a_en: 'Chamamé',
    option_b_es: 'Zamba',
    option_b_en: 'Zamba',
    option_c_es: 'Cueca',
    option_c_en: 'Cueca',
    option_d_es: 'Carnavalito',
    option_d_en: 'Carnavalito',
    correct_answer: 'a'
  },
  {
    id: 'm_d_5',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué característica distingue a la cueca tarijeña?',
    question_en: 'What characteristic distinguishes the Tarija cueca?',
    option_a_es: 'Su ritmo pausado y melodía dulce',
    option_a_en: 'Its slow rhythm and sweet melody',
    option_b_es: 'Su rapidez extrema',
    option_b_en: 'Its extreme speed',
    option_c_es: 'Su estructura sin estribillo',
    option_c_en: 'Its structure without chorus',
    option_d_es: 'Su compás binario',
    option_d_en: 'Its binary measure',
    correct_answer: 'a'
  },
  {
    id: 'm_d_6',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué instrumento de cuerda tiene gran relevancia en las tonadas campesinas?',
    question_en: 'What string instrument has great relevance in peasant songs?',
    option_a_es: 'Violín tarijeño',
    option_a_en: 'Tarija violin',
    option_b_es: 'Arpa',
    option_b_en: 'Harp',
    option_c_es: 'Charango',
    option_c_en: 'Charango',
    option_d_es: 'Bandolín',
    option_d_en: 'Mandolin',
    correct_answer: 'a'
  },
  {
    id: 'm_d_7',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué canto improvisado forma parte del humor popular chapaco?',
    question_en: 'What improvised song is part of chapaco popular humor?',
    option_a_es: 'Copla',
    option_a_en: 'Copla',
    option_b_es: 'Yaraví',
    option_b_en: 'Yaraví',
    option_c_es: 'Romance',
    option_c_en: 'Romance',
    option_d_es: 'Trova',
    option_d_en: 'Trova',
    correct_answer: 'a'
  },
  {
    id: 'm_d_8',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué festival promueve la música tradicional de Méndez y Tarija?',
    question_en: 'What festival promotes the traditional music of Méndez and Tarija?',
    option_a_es: 'Festival del Canto y la Aloja',
    option_a_en: 'Festival of Song and Aloja',
    option_b_es: 'Festival del Charango',
    option_b_en: 'Charango Festival',
    option_c_es: 'Festival de Viña del Mar',
    option_c_en: 'Viña del Mar Festival',
    option_d_es: 'Festival de Coplas del Sur',
    option_d_en: 'Festival of Southern Coplas',
    correct_answer: 'a'
  },
  {
    id: 'm_d_9',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué instrumento combina la influencia indígena y española en su ejecución?',
    question_en: 'What instrument combines indigenous and Spanish influence in its performance?',
    option_a_es: 'Guitarra',
    option_a_en: 'Guitar',
    option_b_es: 'Charango',
    option_b_en: 'Charango',
    option_c_es: 'Quena',
    option_c_en: 'Quena',
    option_d_es: 'Bombo',
    option_d_en: 'Bass drum',
    correct_answer: 'b'
  },
  {
    id: 'm_d_10',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué elemento destaca en las coplas tarijeñas?',
    question_en: 'What element stands out in Tarija coplas?',
    option_a_es: 'El ingenio, la rima y la picardía',
    option_a_en: 'Wit, rhyme and mischief',
    option_b_es: 'La solemnidad',
    option_b_en: 'Solemnity',
    option_c_es: 'El tono religioso',
    option_c_en: 'Religious tone',
    option_d_es: 'La crítica política',
    option_d_en: 'Political criticism',
    correct_answer: 'a'
  },
  {
    id: 'm_d_11',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué danza acompaña frecuentemente a las cuecas chapacas?',
    question_en: 'What dance frequently accompanies chapaca cuecas?',
    option_a_es: 'Zapateo chapaco',
    option_a_en: 'Chapaca tap dancing',
    option_b_es: 'Morenada',
    option_b_en: 'Morenada',
    option_c_es: 'Tinku',
    option_c_en: 'Tinku',
    option_d_es: 'Cueca altiplánica',
    option_d_en: 'Altiplano cueca',
    correct_answer: 'a'
  },
  {
    id: 'm_d_12',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué instrumento de cuerda acompaña casi toda la música chapaca?',
    question_en: 'What string instrument accompanies almost all chapaca music?',
    option_a_es: 'Guitarra',
    option_a_en: 'Guitar',
    option_b_es: 'Charango',
    option_b_en: 'Charango',
    option_c_es: 'Violonchelo',
    option_c_en: 'Cello',
    option_d_es: 'Arpa',
    option_d_en: 'Harp',
    correct_answer: 'a'
  },
  {
    id: 'm_d_13',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué tipo de música se interpreta durante la vendimia tarijeña?',
    question_en: 'What type of music is performed during the Tarija grape harvest?',
    option_a_es: 'Coplas y tonadas tradicionales',
    option_a_en: 'Coplas and traditional songs',
    option_b_es: 'Música urbana',
    option_b_en: 'Urban music',
    option_c_es: 'Baladas románticas',
    option_c_en: 'Romantic ballads',
    option_d_es: 'Música electrónica',
    option_d_en: 'Electronic music',
    correct_answer: 'a'
  },
  {
    id: 'm_d_14',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué valor transmite la música tradicional de la provincia Méndez?',
    question_en: 'What value does the traditional music of Méndez province transmit?',
    option_a_es: 'Identidad, alegría y memoria cultural',
    option_a_en: 'Identity, joy and cultural memory',
    option_b_es: 'Modernidad y globalización',
    option_b_en: 'Modernity and globalization',
    option_c_es: 'Exclusividad urbana',
    option_c_en: 'Urban exclusivity',
    option_d_es: 'Competencia musical',
    option_d_en: 'Musical competition',
    correct_answer: 'a'
  },
  {
    id: 'm_d_15',
    category: 'musica',
    difficulty: 'dificil',
    question_es: '¿Qué papel cumplen las mujeres en las coplas tarijeñas?',
    question_en: 'What role do women play in Tarija coplas?',
    option_a_es: 'Son portadoras del canto popular',
    option_a_en: 'They are carriers of popular song',
    option_b_es: 'No participan',
    option_b_en: 'They do not participate',
    option_c_es: 'Solo bailan',
    option_c_en: 'They only dance',
    option_d_es: 'Tocan percusión',
    option_d_en: 'They play percussion',
    correct_answer: 'a'
  }
];

